config/routes.rb
Rails.application.routes.draw do
  root 'plants#index'
  resources :plants do
    resources :characteristics
  end
  resources :properties
end

app/models/characteristic.rb
class Characteristic < ActiveRecord::Base
  belongs_to :property
  belongs_to :plant
end

app/models/plant.rb
class Plant < ActiveRecord::Base
  has_many :characteristics
  has_many :properties, through: :characteristics
end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :characteristics
  has_many :plants, through: :characteristics
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  enum :purpose => [ :culinary, :medicinal, :utilitarian, :magical ]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characteristics_controller.rb
class CharacteristicsController < ApplicationController
  before_action :set_plant
  before_action :set_characteristic, only: [:edit, :update, :show, :delete]

  def index
    @characteristics = Characteristic.where(:plant_id => @plant.id)
  end

  def new
    @characteristic = Characteristic.new
  end

  def create
    @characteristic = Characteristic.new(characteristic_params)
    if @characteristic.save
      redirect_to plant_characteristics_path(@plant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @characteristic.update(characteristic_params)
      redirect_to plant_characteristics_path(@plant)
    else
      render :edit
    end
  end

  private

  def set_characteristic
    @characteristic = Characteristic.find(params[:id])
  end

  def characteristic_params
    params.require(:characteristic).permit(:property_id, :part, :preparation).merge(:plant_id => @plant.id)
  end

  def set_plant
    @plant = Plant.find(params[:plant_id])
  end

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  def index
    @plants = Plant.all
  end

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)
    if @plant.save
      redirect_to plants_path
    else
      render :new
    end
  end

  def show
    @plant = Plant.find(params[:id])
  end

  def edit
    @plant = Plant.find(params[:id])
  end

  def update
    @plant = Plant.find(params[:id])
    if @plant.update(plant_params)
      redirect_to plant_path(@plant)
    else
      render :edit
    end
  end

  def destroy
    Plant.find(params[:id]).destroy
    redirect_to plants_path
  end

  private

  def plant_params
    params.require(:plant).permit(:common_name, :genus_species)
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy ]

  def index
    @properties = Property.all
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)
    if @property.save
      redirect_to properties_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @property.update(property_params)
      redirect_to properties_path
    else
      render :edit
    end
  end

  def destroy
    @property.delete
    redirect_to properties_path
  end

  private

  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(:name, :description)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_plant, except: [:index, :indexcreate]
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipe = Recipe.new
  end

  def indexcreate
    @recipe = Recipe.new(index_plant_params)
    if @recipe.save
      redirect_to recipe_path
    else
      render :index
    end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(plant_params)
    if @recipe.save
      redirect_to plant_path(@plant)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @recipe.update(plant_params)
      redirect_to plant_recipe_path(@plant, @recipe)
    else
      render :new
    end
  end

  def destroy
    @recipe.destroy
    redirect_to plant_path(@plant)
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def find_plant
    @plant = Plant.find(params[:plant_id])
  end

  def plant_params
    params.require(:recipe).permit(
      :name,
      :part,
      :purpose,
      :ingredients,
      :prep_time,
      :total_time,
      :directions
    ).merge(:plant_id => @plant.id)
  end

  def index_plant_params
    params.require(:recipe).permit(
      :name,
      :part,
      :purpose,
      :ingredients,
      :prep_time,
      :total_time,
      :directions,
      :plant_id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characteristics/edit.html.erb
<h1 class=page-header>Edit <%= @plant.common_name %> Characteristic</h1>

<%= form_for [@plant, @characteristic], html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :property, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.collection_select(:property_id, Property.all, :id, :name, {}, {class: 'form-control'})  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :part, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :part, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :preparation, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :preparation, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit 'Update', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/characteristics/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Add characteristic', new_plant_characteristic_path(@plant), class: "btn btn-success" %>
  </div>
  <h1>Characteristics for <%= @plant.common_name %></h1>
</div>

<table class="table">
  <thead>
    <th>
      Property
    </th>
    <th>
      Plant part
    </th>
    <th>
      Preparation
    </th>
    <th>

    </th>
  </thead>
  <tbody>
    <% @characteristics.each do |characteristic| %>
    <tr>
      <td>
        <%= link_to characteristic.property.name, property_path(characteristic.property) %>
      </td>
      <td>
        <%= characteristic.part %>
      </td>
      <td>
        <%= characteristic.preparation %>
      </td>
      <td>
        <%= link_to 'Edit', edit_plant_characteristic_path(@plant, characteristic) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/characteristics/new.html.erb
<h1 class=page-header>New <%= @plant.common_name %> Characteristic</h1>

<%= form_for [@plant, @characteristic], html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :property, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.collection_select(:property_id, Property.all, :id, :name, {}, {class: 'form-control'})  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :part, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :part, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :preparation, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :preparation, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit 'Create', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsPracticePlants</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Plants</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Menu<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/plants">Plants</a></li>
            <li><a href="/properties">Properties</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/plants/_form.html.erb
<%= render partial: 'shared/errors', locals: {object: @plant} %>

<%= form_for @plant, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :common_name, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :common_name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :genus_species, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :genus_species, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit button, class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/plants/edit.html.erb
<h1 class=page-header>Edit Plant</h1>

<%= render partial: 'form', locals: {button: 'Oops, this is what I meant'} %>

app/views/plants/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'New Plant', new_plant_path, class: "btn btn-success" %>
  </div>
  <h1>Plants</h1>
</div>

<table class="table">
  <thead>
    <th>
      Common Name
    </th>
    <th>
      Genus species
    </th>
  </thead>
  <tbody>
    <% @plants.all.each do |plant| %>
    <tr>
      <td>
        <%= link_to plant.common_name, plant_path(plant) %>
      </td>
      <td>
        <i><%= plant.genus_species %></i>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/plants/new.html.erb
<h1 class=page-header>New Plant</h1>

<%= render partial: 'form', locals: {button: 'I collected that!'} %>

app/views/plants/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'View Characteristics', plant_characteristics_path(@plant), class: 'btn btn-warning' %>
    <%= link_to 'Edit', edit_plant_path(@plant), class: 'btn btn-success' %>
    <%= link_to 'Delete', plant_path(@plant), method: :delete, class: 'btn btn-danger' %>
  </div>
  <h1><%= @plant.common_name %></h1>
</div>

<div class="page-header">
  <div class="pull-right">
    <% @plant.properties.each do |property| %>
      <%= link_to property.name, property_path(property) %>
    <% end %>
  </div>
  <h3><i><%= @plant.genus_species %></i></h3>
</div>

app/views/properties/edit.html.erb
<h1 class=page-header>Edit Property</h1>

<%= form_for @property, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :description, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit 'Update', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/properties/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'New Property', new_property_path, class: "btn btn-success" %>
  </div>
  <h1>Properties</h1>
</div>

<table class="table">
  <thead>
    <th>
      Property Name
    </th>
    <th>
      Property Description
    </th>
  </thead>
  <tbody>
    <% @properties.each do |property| %>
    <tr>
      <td>
        <%= link_to property.name, property_path(property) %>
      </td>
      <td>
        <%= property.description %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/properties/new.html.erb
<h1 class=page-header>New Property</h1>

<%= form_for @property, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :description, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit 'Create', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/properties/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Edit', edit_property_path(@property), class: 'btn btn-success' %>
    <%= link_to 'Delete', property_path(@property), method: :delete, class: 'btn btn-danger' %>
  </div>
  <h1><%= @property.name %></h1>
</div>

<h3><%= @property.description %></h3>

<table class="table">
  <thead>
    <th>
      Plant name
    </th>
    <th>
      Genus Species
    </th>
  </thead>
  <tbody>
    <% @property.plants.each do |plant| %>
      <tr>
        <td>
          <%= link_to plant.common_name, plant_path(plant) %>
        </td>
        <td>
          <i><%= plant.genus_species %></i>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/recipes/edit.html.erb
<h1 class=page-header>Edit <%= @recipe.name %></h1>

<%= form_for [@plant, @recipe], html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Recipe Name', class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :part, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :part, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :purpose, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.select(:purpose, [['Culinary', :culinary], ['Medicinal', :medicinal], ['Utilitarian', :utilitarian], ['Magical', :magical]], {}, {class: 'form-control'})  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ingredients, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :ingredients, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :prep_time, 'Prep Time', class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :prep_time, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :total_time, 'Total Time',  class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :total_time, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :directions, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_area :directions, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit 'Update this recipe', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/recipes/index.html.erb
<h1 class=page-header>Add Recipe</h1>

<%= form_for @recipe, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :plant, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.collection_select :plant_id, Plant.all, :id, :common_name, {}, {class: 'form-control'}  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, 'Recipe Name', class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :part, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :part, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :purpose, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.select(:purpose, [['Culinary', :culinary], ['Medicinal', :medicinal], ['Utilitarian', :utilitarian], ['Magical', :magical]], {}, {class: 'form-control'})  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ingredients, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :ingredients, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :prep_time, 'Prep Time', class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :prep_time, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :total_time, 'Total Time',  class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :total_time, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :directions, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_area :directions, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit 'That is how you make it', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<h1 class=page-header>New <%= @plant.common_name %> Recipe</h1>

<%= form_for [@plant, @recipe], html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Recipe Name', class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :part, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :part, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :purpose, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.select(:purpose, [['Culinary', :culinary], ['Medicinal', :medicinal], ['Utilitarian', :utilitarian], ['Magical', :magical]], {}, {class: 'form-control'})  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ingredients, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :ingredients, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :prep_time, 'Prep Time', class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :prep_time, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :total_time, 'Total Time',  class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_field :total_time, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :directions, class: 'col-md-2 control-label' %>
    <div class='col-md-6'>
      <%= f.text_area :directions, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit 'That is how you make it', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/recipes/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Edit', edit_plant_recipe_path(@plant, @recipe), class: 'btn btn-success' %>
    <%= link_to 'Delete', plant_recipe_path(@plant, @recipe), method: :delete, class: 'btn btn-danger' %>
  </div>
  <h1><%= @recipe.name %></h1>
</div>

<h3>For <i><%= @plant.genus_species %></i>, commonly known as <%= @plant.common_name %></h3>

<h4 class="page-header">Recipe</h4>

<dl class="dl-horizontal">
  <dt>Recipe Name</dt>
  <dd><%= @recipe.name %></dd>
  <dt>Plant Part</dt>
  <dd><%= @recipe.part %></dd>
  <dt>Purpose</dt>
  <dd><%= @recipe.purpose.capitalize %></dd>
  <dt>Ingredients</dt>
  <dd><%= @recipe.ingredients%></dd>
  <dt>Prep Time</dt>
  <dd><%= @recipe.prep_time %></dd>
  <dt>Total Time</dt>
  <dd><%= @recipe.total_time%></dd>
  <dt>Directions</dt>
  <dd><%= @recipe.directions%></dd>
</dl>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>